---
- name: install npm and nodejs
  hosts: 95.40.36.149
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: update apt 
      apt: 
        update_cache: yes
        upgrade: full
    - name: install pkg
      apt:
        pkg:
        - npm
        - docker.io
        - nodejs
- name: upload tar and unarchive tar
  hosts: 95.40.36.149
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: unarchive tar
      unarchive:
        src: /Users/yiran/Documents/Learning/Ansible/ansible-backup.tar.gz
        dest: /root/
    - name: docker nginx start 
      ansible.builtin.command: docker run -d -p 80:80 nginx
      async: 1000
      poll: 0
    - name: nginx status check
      shell: docker ps 
      register: dir_path
    - debug: msg={{dir_path}}


