#SPDX-License-Identifier: MIT-0
---
# tasks file for my_docker_role
- name: check ansible availability
  wait_for:
    delay: 10
    port: 22
    timeout: 120
    host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
    search_regex: OpenSSH
