---
- name: deploy nexus 
  vars_files: 
    - nexus_variables.yaml
  hosts: "{{server_ip}}"
  become: yes
  become_user: root
  tasks: 
    - name: apt update and install dependance 
      apt: 
        update_cache: true
        pkg: 
        - openjdk-8-jre-headless
        - net-tools
    - name: download nexus package
      get_url: 
        url: "{{nexus_package_url}}"
        dest: /opt/
      register: nexus_package_info
    - name: unpack the extract file
      unarchive:
        src: "{{nexus_package_info.dest}}"
        dest: /opt/
        remote_src: yes
    - name: find the unpackage name diretory
      find: 
        path: /opt/
        file_type: directory
        patterns: 'nexus*'
      register: nexus_package_name
    - name: check the path folder
      stat:
        path: /opt/nexus 
      register: path_folder
    - name: rename the directory
      shell: mv {{nexus_package_name.files[0].path}} /opt/nexus
      when: path_folder.stat.exists == false
