pipeline{ 
    agent any 
    environment{
        ANSIBLE_SERVER_IP = "54.46.46.221"
    }
    stages{
        stage('ssh service'){
            steps{
                script{
                    sshagent (credentials: ['ansible-server']) {
                        sh 'scp ./ansible/* ec2@${ANSIBLE_SERVER_IP}:/home/ec2-user/ansible/'
                        
                    }
                }
            }
        }
    }
}
