---
plugin: amazon.aws.aws_ec2
regions:
  - ap-east-1
filters:
  instance-state-name: running
#   tag:Name:
#     - jenkins-triggered
keyed_groups:
  - key: tags.Name
    prefix: ec2

groups:
  target_servers: "'ec2_jenkins_triggered' in aws_groups"